# Generated by Django 6.0.5 on 2026-06-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_label'),
        ('expenses', '0002_expense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='categories.label'),
        ),
    ]
