# Generated by Django 6.0.6 on 2026-06-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_parent_subcategory'),
        ('expenses', '0003_expense_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='categories.subcategory'),
        ),
    ]
