# Generated by Django 6.0.6 on 2026-06-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='labels',
        ),
    ]
