# Generated by Django 6.0.5 on 2026-06-06 07:56

from django.db import migrations, models


def migrate_account_types(apps, schema_editor):
    """Migrate old account types to new consolidated types."""
    Account = apps.get_model('accounts', 'Account')
    type_mapping = {
        'GPay': 'UPI',
        'PhonePe': 'UPI',
        'Debit Card': 'Credit Card',
        'Other Wallets': 'Wallet',
    }
    for old_type, new_type in type_mapping.items():
        Account.objects.filter(account_type=old_type).update(account_type=new_type)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_notes'),
    ]

    operations = [
        migrations.RunPython(migrate_account_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Account', 'Bank Account'), ('Wallet', 'Wallet'), ('Credit Card', 'Credit Card'), ('UPI', 'UPI')], max_length=50),
        ),
    ]
