# Generated by Django 6.0.5 on 2026-06-06 08:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='minimum_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
