# Generated by Django 6.0.5 on 2026-06-08 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_minimum_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('₹', 'INR (₹)'), ('$', 'USD ($)'), ('€', 'EUR (€)'), ('£', 'GBP (£)'), ('¥', 'JPY (¥)')], default='₹', max_length=5)),
                ('budget_threshold', models.IntegerField(default=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
