# Generated by Django 6.0.5 on 2026-06-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='low_balance_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
