# Generated by Django 6.0.5 on 2026-06-08 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usersettings_low_balance_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='enable_budget_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='budget_threshold',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
