# Generated by Django 6.0.5 on 2026-06-08 09:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usersettings_enable_budget_alerts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='low_balance_alert_scope',
            field=models.CharField(choices=[('all', 'All Accounts'), ('active', 'Active Accounts Only'), ('non_zero', 'Accounts with Transactions Only')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='low_balance_default_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Default minimum balance applied when creating new accounts (0 = disabled).', max_digits=12),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='low_balance_show_dashboard_banner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='low_balance_show_dashboard_panel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='low_balance_show_navbar_badge',
            field=models.BooleanField(default=True),
        ),
    ]
