# Generated by Django 6.0.5 on 2026-06-08 10:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_low_balance_alert_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='budget_threshold',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='budget_remaining_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1000.00'), help_text='Alert when remaining budget drops below this amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
