# Generated by Django 6.0.5 on 2026-06-08 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_usersettings_budget_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='budget_remaining_threshold',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='budget_threshold',
            field=models.IntegerField(default=80, help_text='Notify when any budget reaches this % of usage. (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
