# Generated by Django 6.0.6 on 2026-06-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_usersettings_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='hide_uncategorized',
            field=models.BooleanField(default=False, help_text='Hide uncategorized expenses from reports, dashboards, and transaction lists.'),
        ),
    ]
