# Generated by Django 6.0.6 on 2026-06-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_usersettings_hide_uncategorized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='budget_threshold',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='enable_budget_alerts',
        ),
    ]
