# Generated by Django 6.0.6 on 2026-06-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_usersettings_budget_threshold_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountTransfer',
        ),
    ]
