# Generated by Django 6.0.6 on 2026-06-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_delete_accounttransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='hide_uncategorized',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='low_balance_alert_scope',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='low_balance_alerts',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='low_balance_default_minimum',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='low_balance_show_dashboard_banner',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='low_balance_show_dashboard_panel',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='low_balance_show_navbar_badge',
        ),
    ]
