# Generated by Django 6.0.6 on 2026-06-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_parent_subcategory'),
        ('expenses', '0006_remove_expense_labels'),
        ('income', '0004_remove_income_labels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
