"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-p)+=suxatfa@r($_8-g)yoc0p_7ih-^oo7*d85lq!iy=#50v2!')

# SECURITY WARNING: don't run with debug turned on in production!
# Force DEBUG=False on Vercel unless explicitly overridden to True via environment variable
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 't')
if os.environ.get('VERCEL') == '1':
    DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

if DEBUG:
    ALLOWED_HOSTS.append('*')
else:
    # Production hosts
    vercel_url = os.environ.get('VERCEL_URL')
    if vercel_url:
        ALLOWED_HOSTS.append(vercel_url)
    ALLOWED_HOSTS.append('.vercel.app')
    
    # Custom hosts via environment variable
    env_hosts = os.environ.get('ALLOWED_HOSTS')
    if env_hosts:
        ALLOWED_HOSTS.extend([host.strip() for host in env_hosts.split(',') if host.strip()])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts.apps.AccountsConfig',
    'income.apps.IncomeConfig',
    'expenses.apps.ExpensesConfig',
    'categories.apps.CategoriesConfig',
    'dashboard.apps.DashboardConfig',
    'reports.apps.ReportsConfig',
    'transactions.apps.TransactionsConfig',
    'budgets.apps.BudgetsConfig',
    'companies.apps.CompaniesConfig',
    'goals.apps.GoalsConfig',
    'debts.apps.DebtsConfig',
    'recurrences.apps.RecurrencesConfig',
    'analytics.apps.AnalyticsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'recurrences.middleware.RecurringTransactionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_settings',
                'budgets.context_processors.budget_alerts_processor',
                'accounts.context_processors.global_forms',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import sys

# Force PostgreSQL when running in production or Vercel
is_vercel = 'VERCEL' in os.environ or 'VERCEL_ENV' in os.environ
is_production = not DEBUG or is_vercel

db_url = os.environ.get('DATABASE_URL') or os.environ.get('POSTGRES_URL')

# Startup logging to stderr (Vercel function logs)
print("--- [STARTUP LOGGING: DATABASE CONFIGURATION] ---", file=sys.stderr)
print(f"DEBUG status: {DEBUG}", file=sys.stderr)
print(f"VERCEL environment detected: {is_vercel}", file=sys.stderr)
print(f"Is Production environment: {is_production}", file=sys.stderr)
print(f"DATABASE_URL configured: {bool(os.environ.get('DATABASE_URL'))}", file=sys.stderr)
print(f"POSTGRES_URL configured: {bool(os.environ.get('POSTGRES_URL'))}", file=sys.stderr)

if db_url:
    try:
        DATABASES = {
            'default': dj_database_url.config(
                default=db_url,
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
        # Enforce PostgreSQL engine and SSL in production
        DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
        if not DEBUG:
            DATABASES['default']['OPTIONS'] = {
                'sslmode': 'require',
            }
    except Exception as e:
        from django.core.exceptions import ImproperlyConfigured
        print(f"DATABASE CONFIG ERROR: {e}", file=sys.stderr)
        raise ImproperlyConfigured(f"Failed to configure PostgreSQL from DATABASE_URL: {e}")
elif is_production:
    from django.core.exceptions import ImproperlyConfigured
    err_msg = (
        "Database connection URL is missing! You are running in a production or Vercel environment, "
        "but neither 'DATABASE_URL' nor 'POSTGRES_URL' environment variables are configured. "
        "Please add your PostgreSQL connection string in the Vercel Project Settings."
    )
    print(f"DATABASE CONFIG ERROR: {err_msg}", file=sys.stderr)
    raise ImproperlyConfigured(err_msg)
else:
    # Fall back to SQLite for local development only
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

print(f"Active Database Engine: {DATABASES['default']['ENGINE']}", file=sys.stderr)
print("-------------------------------------------------", file=sys.stderr)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise storage configuration for compressed and cached static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

WHITENOISE_MANIFEST_STRICT = False

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication Settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


