# Generated by Django 6.0.5 on 2026-06-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_label'),
        ('income', '0002_income_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='incomes', to='categories.label'),
        ),
    ]
