# Generated by Django 6.0.6 on 2026-06-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_income_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='labels',
        ),
    ]
