# Generated by Django 6.0.6 on 2026-06-29 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_unique_together_and_more'),
        ('income', '0004_remove_income_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'income'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='categories.category'),
        ),
    ]
