# Generated by Django 6.0.6 on 2026-06-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_income_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
